// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'api_key',
    appId: 'api_id',
    messagingSenderId: '1091055234839',
    projectId: 'falldetectionapp-851a4',
    authDomain: 'falldetectionapp-851a4.firebaseapp.com',
    databaseURL: 'url',
    storageBucket: 'falldetectionapp-851a4.firebasestorage.app',
    measurementId: 'G-G3TGJ53ZDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'api_key',
    appId: '1:1091055234839:android:ae44e00a698774ad88d152',
    messagingSenderId: '1091055234839',
    projectId: 'falldetectionapp-851a4',
    databaseURL: 'sss',
    storageBucket: 'falldetectionapp-851a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6XJxsUQCGNf-z3Y1BSAWwIfHwO-wr-ck',
    appId: '1:1091055234839:ios:0a44c988b009940888d152',
    messagingSenderId: '1091055234839',
    projectId: 'falldetectionapp-851a4',
    databaseURL: 'https://falldetectionapp-851a4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'falldetectionapp-851a4.firebasestorage.app',
    iosBundleId: 'com.example.fallDetectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6XJxsUQCGNf-z3Y1BSAWwIfHwO-wr-ck',
    appId: '1:1091055234839:ios:0a44c988b009940888d152',
    messagingSenderId: '1091055234839',
    projectId: 'falldetectionapp-851a4',
    databaseURL: 'https://falldetectionapp-851a4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'falldetectionapp-851a4.firebasestorage.app',
    iosBundleId: 'com.example.fallDetectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuwsGG8kA0tQUG9hbMPg8tPR-Oh1sa-V8',
    appId: '1:1091055234839:web:8480c9270c66185988d152',
    messagingSenderId: '1091055234839',
    projectId: 'falldetectionapp-851a4',
    authDomain: 'falldetectionapp-851a4.firebaseapp.com',
    databaseURL: 'https://falldetectionapp-851a4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'falldetectionapp-851a4.firebasestorage.app',
    measurementId: 'G-95RL80LHFG',
  );
}
